FROM mcr.microsoft.com/playwright:v1.49.1-jammy

RUN npm install -g pnpm

# Set user created by playwright image for non-root execution
USER pwuser

WORKDIR /usr/src/app

# Cache package installation
COPY --chown=pwuser:pwuser package.json pnpm-lock.yaml ./
RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "run", "test"]
