import type { Metadata } from 'next';
import './globals.css';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <head>{/* <script src="https://unpkg.com/react-scan/dist/auto.global.js" async /> */}</head>

    {children}
  </html>
);

export default RootLayout;
