export enum RouteScreensEnum {
  'dashboard' = '/admin/dashboard',
  'login' = '/login',
  'register' = '/register',
  'root' = '/',
  'publicPosts' = '/posts',
  'publicMaps' = '/map',
  'posts' = '/admin/posts',
  'data' = '/admin/data',
  'createPost' = '/admin/createPost',
  'suggestions' = '/admin/suggestions',
  'profile' = '/admin/profile',
  'saved' = '/saved',
  'tested' = '/tested',
}
