import type { Metadata } from 'next';
import React from 'react';
import { Footer } from '@/organisms/Footer';
import { PrivateHeaderClient } from '@/organisms/PrivateHeader/PrivateHeaderClient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  // Busca sessão server-side - sem loading state, sem flash
  // const session = {} //await getSession();

  // Se não autenticado, redireciona antes de renderizar qualquer coisa
  // if (!session) redirect('/login');

  return (
    <div className="min-h-screen flex flex-col">
      <PrivateHeaderClient user={{ name: 'Mock Server User' }} />
      <main className="flex-1 flex items-center justify-center px-3xl py-3xl bg-content-bg border border-border-soft shadow-md rounded-sm">
        {children}
      </main>

      <Footer />
    </div>
  );
};

export default RootLayout;
