import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { PublicHeader } from '@/organisms/PublicHeader';
import { Footer } from '@/organisms/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RegisterPage = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    // <body className="bg-root-bg ">
    <div className="flex flex-col justify-between min-h-screen">
      <PublicHeader />

      <div className="mt-5xl flex items-start justify-center animate-fadeIn300 flex-1">
        <main className="flex flex-col max-w-content-desktop w-full px-3xl py-3xl gap-3xl bg-content-bg border border-neutral-800 shadow-md rounded-sm">
          {children}
        </main>
      </div>

      <Footer />
    </div>
    // </body>
  );
};

export default RegisterPage;
