import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { PublicHeader } from '@/organisms/PublicHeader';
import { Footer } from '@/organisms/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RegisterPage = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <>
      <PublicHeader />

      <main className="pt-28 md:pt-32 flex-1 flex flex-col">{children}</main>

      <Footer />
    </>
  );
};

export default RegisterPage;
