name: BDD

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  bdd:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run BDD Tests
        run: pnpm run test:bdd
