name: check tsc and lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment

      - run: pnpm type-check
      - run: pnpm lint
      - run: pnpm stylelint "**.css"
